# https://docusaurus.io/docs/deployment#triggering-deployment-with-github-actions
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm i
      - name: Build website
        run: npm run build

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.2
        with:
          # Should this action only emit build telemetry instead of deploying the build artifact?
          emit_telemetry: # optional, default is false
          # The status of the previous build.
          conclusion: # optional
          # GitHub token
          token: # default is ${{ github.token }}
          # Time in milliseconds after which to timeout and cancel the deployment (default: 10 minutes)
          timeout: # optional, default is 600000
          # Maximum number of status report errors before cancelling a deployment (default: 10)
          error_count: # optional, default is 10
          # Time in milliseconds between two deployment status report (default: 5 seconds)
          reporting_interval: # optional, default is 5000
          # Name of the artifact to deploy
          artifact_name: # optional, default is github-pages
          # Is this attempting to deploy a pull request as a GitHub Pages preview site? (NOTE: This feature is only in alpha currently and is not available to the public!)
          preview: # optional, default is false
      
      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./build
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
